- name: Generate config files and docker compose
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/main.yaml
  vars:
    csv_file: "{{ playbook_dir }}/config-generator/test-mme.csv"

  tasks:

    - name: Generate config files
      import_tasks: tasks/generate-configs.yaml
      tags:
        - generate-configs

    - name: Read CSV data
      community.general.read_csv:
        path: "{{ csv_file }}"
        delimiter: ','
      register: csv_data
      tags:
        - generate-compose

    - name: Configure docker compose file
      import_tasks: tasks/generate-compose.yaml
      tags:
        - generate-compose
